### ISSUE TITLE
Fight System

### ISSUE THREAD

**Issue by sc2insane** [momower1/IMGE-Game#10]
- [x] add throwable objects
- [x] finish hitbox/hurtbox detection
- [x] rumble motor

**Comment by momower1** [comment]
@sc2insane add rumble motor when being hit or sth else?

**Comment by momower1** [comment]
@sc2insane the slider throw should be faster when moving (maybe add slider velocity to current player velocity?) and I don't like the fact that you can throw behind you while moving 🔨

**Comment by sc2insane** [comment]
@momower1 I am not going to change the fact that you can throw behind while moving, but I can add the player's velocity.

**Comment by momower1** [comment]
@sc2insane please add colliders to players so you cannot run through the other player. Plus there is allways a NullReferenceException with the zzone...

**Comment by sc2insane** [comment]
i don't get any NullReferenceExceptions, when does this happen to you?

**Comment by momower1** [comment]
@sc2insane after like 1min of playing i have about 100+ exceptions
