### ISSUE TITLE
Player Behaviour

### ISSUE THREAD

**Issue by sc2insane** [momower1/IMGE-Game#11]
- [x] Interaction with drops
- [x] add animations to behaviour
- [x] implement special attack
- [x] respawn

**Comment by momower1** [comment]
@sc2insane add LED functionality on controller with HP and special attack, manage respawn?

**Comment by momower1** [comment]
@sc2insane the slider throw should be faster when moving (maybe add slider velocity to current player velocity?) and I don't like the fact that you can throw behind you while moving 🔨
